
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package cup;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int GET_MOVES_COUNT = 39;
  public static final int SUCCESSFUL_DEFENSE = 31;
  public static final int LOW_HEALTH_VICTORY = 38;
  public static final int RANDOM = 28;
  public static final int WITH = 16;
  public static final int GE = 47;
  public static final int ACCION_GUERRERO = 44;
  public static final int ACCION_MAGO = 43;
  public static final int FAILED_ACTION_PENALTY = 33;
  public static final int ENTERO = 63;
  public static final int WARRIOR_COMBO = 37;
  public static final int OPPONENT_RESOURCE = 21;
  public static final int CORCHETEC = 59;
  public static final int SELF_RESOURCE = 20;
  public static final int SCORING = 12;
  public static final int MAGE = 2;
  public static final int CORCHETEA = 58;
  public static final int OJOS = 60;
  public static final int DAMAGE_POINT = 29;
  public static final int MAGE_COMBO = 35;
  public static final int PARENTESISC = 57;
  public static final int MATCH = 9;
  public static final int RULES = 5;
  public static final int PARENTESISA = 56;
  public static final int NOT = 53;
  public static final int AND = 51;
  public static final int LT = 50;
  public static final int GET_LAST_N_MOVES = 40;
  public static final int OR = 52;
  public static final int VICTORY_BONUS = 32;
  public static final int OPPONENT_SCORE = 23;
  public static final int MAIN = 14;
  public static final int IF = 6;
  public static final int ID = 64;
  public static final int LE = 48;
  public static final int BONUSES = 13;
  public static final int INITIAL = 4;
  public static final int DECIMAL = 62;
  public static final int EOF = 0;
  public static final int ROUNDS = 11;
  public static final int error = 1;
  public static final int COMA = 61;
  public static final int PLAYERS = 10;
  public static final int TOTAL_ROUNDS = 25;
  public static final int NEQ = 46;
  public static final int EQ = 45;
  public static final int SELF_HEALTH = 18;
  public static final int SELF_HISTORY = 26;
  public static final int ROUND_NUMBER = 24;
  public static final int LAST_MOVE = 42;
  public static final int WARRIOR_COMBO_POINTS = 36;
  public static final int ELSE = 8;
  public static final int OPPONENT_HEALTH = 19;
  public static final int GET_MOVE = 41;
  public static final int THEN = 7;
  public static final int SEED = 17;
  public static final int WARRIOR = 3;
  public static final int OPPONENT_HISTORY = 27;
  public static final int LLAVEC = 55;
  public static final int GT = 49;
  public static final int MAGE_COMBO_POINTS = 34;
  public static final int RUN = 15;
  public static final int SELF_SCORE = 22;
  public static final int LLAVEA = 54;
  public static final int HEALING_POINT = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAGE",
  "WARRIOR",
  "INITIAL",
  "RULES",
  "IF",
  "THEN",
  "ELSE",
  "MATCH",
  "PLAYERS",
  "ROUNDS",
  "SCORING",
  "BONUSES",
  "MAIN",
  "RUN",
  "WITH",
  "SEED",
  "SELF_HEALTH",
  "OPPONENT_HEALTH",
  "SELF_RESOURCE",
  "OPPONENT_RESOURCE",
  "SELF_SCORE",
  "OPPONENT_SCORE",
  "ROUND_NUMBER",
  "TOTAL_ROUNDS",
  "SELF_HISTORY",
  "OPPONENT_HISTORY",
  "RANDOM",
  "DAMAGE_POINT",
  "HEALING_POINT",
  "SUCCESSFUL_DEFENSE",
  "VICTORY_BONUS",
  "FAILED_ACTION_PENALTY",
  "MAGE_COMBO_POINTS",
  "MAGE_COMBO",
  "WARRIOR_COMBO_POINTS",
  "WARRIOR_COMBO",
  "LOW_HEALTH_VICTORY",
  "GET_MOVES_COUNT",
  "GET_LAST_N_MOVES",
  "GET_MOVE",
  "LAST_MOVE",
  "ACCION_MAGO",
  "ACCION_GUERRERO",
  "EQ",
  "NEQ",
  "GE",
  "LE",
  "GT",
  "LT",
  "AND",
  "OR",
  "NOT",
  "LLAVEA",
  "LLAVEC",
  "PARENTESISA",
  "PARENTESISC",
  "CORCHETEA",
  "CORCHETEC",
  "OJOS",
  "COMA",
  "DECIMAL",
  "ENTERO",
  "ID"
  };
}

