
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyzer;

import java_cup.runtime.Symbol;
import java.util.ArrayList;
import java.util.List;
import battlescript.model.*;
import engine.context.Context;
import engine.expressions.*;
import engine.rules.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\107\000\002\002\004\000\002\002\005\000\002\003" +
    "\003\000\002\003\004\000\002\003\002\000\002\004\003" +
    "\000\002\004\004\000\002\004\002\000\002\005\012\000" +
    "\002\005\012\000\002\010\003\000\002\011\003\000\002" +
    "\012\011\000\002\014\003\000\002\014\005\000\002\014" +
    "\002\000\002\013\006\000\002\015\011\000\002\017\003" +
    "\000\002\017\005\000\002\017\002\000\002\016\006\000" +
    "\002\006\024\000\002\020\031\000\002\021\035\000\002" +
    "\022\003\000\002\022\005\000\002\022\003\000\002\022" +
    "\005\000\002\007\006\000\002\023\003\000\002\023\004" +
    "\000\002\023\002\000\002\024\014\000\002\025\003\000" +
    "\002\025\005\000\002\026\003\000\002\027\005\000\002" +
    "\027\003\000\002\030\005\000\002\030\003\000\002\031" +
    "\005\000\002\031\005\000\002\031\005\000\002\031\005" +
    "\000\002\031\005\000\002\031\005\000\002\031\003\000" +
    "\002\032\004\000\002\032\003\000\002\033\003\000\002" +
    "\033\003\000\002\033\003\000\002\033\003\000\002\033" +
    "\003\000\002\033\003\000\002\033\003\000\002\033\003" +
    "\000\002\033\003\000\002\033\003\000\002\033\003\000" +
    "\002\033\003\000\002\033\003\000\002\033\005\000\002" +
    "\034\010\000\002\034\006\000\002\034\010\000\002\034" +
    "\010\000\002\034\010\000\002\035\003\000\002\035\003" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\325\000\012\004\010\005\004\013\ufffd\020\ufffd\001" +
    "\002\000\004\102\303\001\002\000\004\002\302\001\002" +
    "\000\012\004\uffff\005\uffff\013\uffff\020\uffff\001\002\000" +
    "\012\004\010\005\004\013\141\020\ufffa\001\002\000\004" +
    "\102\011\001\002\000\004\070\012\001\002\000\004\006" +
    "\013\001\002\000\004\076\014\001\002\000\004\055\016" +
    "\001\002\000\004\007\017\001\002\000\016\007\ufff7\010" +
    "\ufff7\012\ufff7\073\ufff7\075\ufff7\077\ufff7\001\002\000\004" +
    "\076\022\001\002\000\004\071\021\001\002\000\012\004" +
    "\ufff9\005\ufff9\013\ufff9\020\ufff9\001\002\000\004\074\023" +
    "\001\002\000\006\010\026\012\ufff2\001\002\000\006\010" +
    "\026\012\135\001\002\000\006\010\ufff4\012\ufff4\001\002" +
    "\000\046\024\041\025\050\026\052\027\046\030\047\031" +
    "\032\032\054\033\040\036\051\051\042\052\027\053\036" +
    "\054\044\067\035\072\056\100\031\101\053\102\043\001" +
    "\002\000\004\072\127\001\002\000\010\011\uffdd\066\125" +
    "\073\uffdd\001\002\000\026\011\uffce\057\uffce\060\uffce\061" +
    "\uffce\062\uffce\063\uffce\064\uffce\065\uffce\066\uffce\073\uffce" +
    "\001\002\000\026\011\uffc8\057\uffc8\060\uffc8\061\uffc8\062" +
    "\uffc8\063\uffc8\064\uffc8\065\uffc8\066\uffc8\073\uffc8\001\002" +
    "\000\026\011\uffd0\057\uffd0\060\uffd0\061\uffd0\062\uffd0\063" +
    "\uffd0\064\uffd0\065\uffd0\066\uffd0\073\uffd0\001\002\000\004" +
    "\011\123\001\002\000\046\024\041\025\050\026\052\027" +
    "\046\030\047\031\032\032\054\033\040\036\051\051\042" +
    "\052\027\053\036\054\044\067\035\072\056\100\031\101" +
    "\053\102\043\001\002\000\004\072\115\001\002\000\026" +
    "\011\uffd2\057\101\060\106\061\105\062\104\063\103\064" +
    "\102\065\uffd2\066\uffd2\073\uffd2\001\002\000\026\011\uffc6" +
    "\057\uffc6\060\uffc6\061\uffc6\062\uffc6\063\uffc6\064\uffc6\065" +
    "\uffc6\066\uffc6\073\uffc6\001\002\000\026\011\uffcd\057\uffcd" +
    "\060\uffcd\061\uffcd\062\uffcd\063\uffcd\064\uffcd\065\uffcd\066" +
    "\uffcd\073\uffcd\001\002\000\004\072\071\001\002\000\026" +
    "\011\uffc4\057\uffc4\060\uffc4\061\uffc4\062\uffc4\063\uffc4\064" +
    "\uffc4\065\uffc4\066\uffc4\073\uffc4\001\002\000\004\072\064" +
    "\001\002\000\012\011\uffdb\065\062\066\uffdb\073\uffdb\001" +
    "\002\000\026\011\uffca\057\uffca\060\uffca\061\uffca\062\uffca" +
    "\063\uffca\064\uffca\065\uffca\066\uffca\073\uffca\001\002\000" +
    "\026\011\uffc9\057\uffc9\060\uffc9\061\uffc9\062\uffc9\063\uffc9" +
    "\064\uffc9\065\uffc9\066\uffc9\073\uffc9\001\002\000\026\011" +
    "\uffcc\057\uffcc\060\uffcc\061\uffcc\062\uffcc\063\uffcc\064\uffcc" +
    "\065\uffcc\066\uffcc\073\uffcc\001\002\000\026\011\uffc5\057" +
    "\uffc5\060\uffc5\061\uffc5\062\uffc5\063\uffc5\064\uffc5\065\uffc5" +
    "\066\uffc5\073\uffc5\001\002\000\026\011\uffcb\057\uffcb\060" +
    "\uffcb\061\uffcb\062\uffcb\063\uffcb\064\uffcb\065\uffcb\066\uffcb" +
    "\073\uffcb\001\002\000\026\011\uffcf\057\uffcf\060\uffcf\061" +
    "\uffcf\062\uffcf\063\uffcf\064\uffcf\065\uffcf\066\uffcf\073\uffcf" +
    "\001\002\000\026\011\uffc7\057\uffc7\060\uffc7\061\uffc7\062" +
    "\uffc7\063\uffc7\064\uffc7\065\uffc7\066\uffc7\073\uffc7\001\002" +
    "\000\012\011\uffd9\065\uffd9\066\uffd9\073\uffd9\001\002\000" +
    "\046\024\041\025\050\026\052\027\046\030\047\031\032" +
    "\032\054\033\040\036\051\051\042\052\027\053\036\054" +
    "\044\067\035\072\056\100\031\101\053\102\043\001\002" +
    "\000\026\011\uffc3\057\uffc3\060\uffc3\061\uffc3\062\uffc3\063" +
    "\uffc3\064\uffc3\065\uffc3\066\uffc3\073\uffc3\001\002\000\004" +
    "\073\061\001\002\000\026\011\uffc2\057\uffc2\060\uffc2\061" +
    "\uffc2\062\uffc2\063\uffc2\064\uffc2\065\uffc2\066\uffc2\073\uffc2" +
    "\001\002\000\046\024\041\025\050\026\052\027\046\030" +
    "\047\031\032\032\054\033\040\036\051\051\042\052\027" +
    "\053\036\054\044\067\035\072\056\100\031\101\053\102" +
    "\043\001\002\000\012\011\uffda\065\uffda\066\uffda\073\uffda" +
    "\001\002\000\006\034\066\035\067\001\002\000\004\073" +
    "\070\001\002\000\006\073\uffbc\077\uffbc\001\002\000\006" +
    "\073\uffbb\077\uffbb\001\002\000\026\011\uffc0\057\uffc0\060" +
    "\uffc0\061\uffc0\062\uffc0\063\uffc0\064\uffc0\065\uffc0\066\uffc0" +
    "\073\uffc0\001\002\000\006\034\066\035\067\001\002\000" +
    "\004\077\073\001\002\000\006\055\016\056\074\001\002" +
    "\000\016\007\ufff6\010\ufff6\012\ufff6\073\ufff6\075\ufff6\077" +
    "\ufff6\001\002\000\004\073\100\001\002\000\004\073\077" +
    "\001\002\000\026\011\uffbe\057\uffbe\060\uffbe\061\uffbe\062" +
    "\uffbe\063\uffbe\064\uffbe\065\uffbe\066\uffbe\073\uffbe\001\002" +
    "\000\026\011\uffbf\057\uffbf\060\uffbf\061\uffbf\062\uffbf\063" +
    "\uffbf\064\uffbf\065\uffbf\066\uffbf\073\uffbf\001\002\000\046" +
    "\024\041\025\050\026\052\027\046\030\047\031\032\032" +
    "\054\033\040\036\051\051\042\052\027\053\036\054\044" +
    "\067\035\072\056\100\031\101\053\102\043\001\002\000" +
    "\046\024\041\025\050\026\052\027\046\030\047\031\032" +
    "\032\054\033\040\036\051\051\042\052\027\053\036\054" +
    "\044\067\035\072\056\100\031\101\053\102\043\001\002" +
    "\000\046\024\041\025\050\026\052\027\046\030\047\031" +
    "\032\032\054\033\040\036\051\051\042\052\027\053\036" +
    "\054\044\067\035\072\056\100\031\101\053\102\043\001" +
    "\002\000\046\024\041\025\050\026\052\027\046\030\047" +
    "\031\032\032\054\033\040\036\051\051\042\052\027\053" +
    "\036\054\044\067\035\072\056\100\031\101\053\102\043" +
    "\001\002\000\046\024\041\025\050\026\052\027\046\030" +
    "\047\031\032\032\054\033\040\036\051\051\042\052\027" +
    "\053\036\054\044\067\035\072\056\100\031\101\053\102" +
    "\043\001\002\000\046\024\041\025\050\026\052\027\046" +
    "\030\047\031\032\032\054\033\040\036\051\051\042\052" +
    "\027\053\036\054\044\067\035\072\056\100\031\101\053" +
    "\102\043\001\002\000\012\011\uffd7\065\uffd7\066\uffd7\073" +
    "\uffd7\001\002\000\012\011\uffd3\065\uffd3\066\uffd3\073\uffd3" +
    "\001\002\000\012\011\uffd4\065\uffd4\066\uffd4\073\uffd4\001" +
    "\002\000\012\011\uffd5\065\uffd5\066\uffd5\073\uffd5\001\002" +
    "\000\012\011\uffd6\065\uffd6\066\uffd6\073\uffd6\001\002\000" +
    "\012\011\uffd8\065\uffd8\066\uffd8\073\uffd8\001\002\000\006" +
    "\034\066\035\067\001\002\000\004\077\117\001\002\000" +
    "\004\101\120\001\002\000\004\073\121\001\002\000\026" +
    "\011\uffc1\057\uffc1\060\uffc1\061\uffc1\062\uffc1\063\uffc1\064" +
    "\uffc1\065\uffc1\066\uffc1\073\uffc1\001\002\000\026\011\uffd1" +
    "\057\uffd1\060\uffd1\061\uffd1\062\uffd1\063\uffd1\064\uffd1\065" +
    "\uffd1\066\uffd1\073\uffd1\001\002\000\004\055\016\001\002" +
    "\000\010\010\ufff1\012\ufff1\077\ufff1\001\002\000\046\024" +
    "\041\025\050\026\052\027\046\030\047\031\032\032\054" +
    "\033\040\036\051\051\042\052\027\053\036\054\044\067" +
    "\035\072\056\100\031\101\053\102\043\001\002\000\012" +
    "\011\uffdc\065\062\066\uffdc\073\uffdc\001\002\000\006\034" +
    "\066\035\067\001\002\000\004\077\131\001\002\000\004" +
    "\101\132\001\002\000\004\073\133\001\002\000\026\011" +
    "\uffbd\057\uffbd\060\uffbd\061\uffbd\062\uffbd\063\uffbd\064\uffbd" +
    "\065\uffbd\066\uffbd\073\uffbd\001\002\000\004\077\140\001" +
    "\002\000\004\055\016\001\002\000\004\075\137\001\002" +
    "\000\004\071\ufff5\001\002\000\006\010\ufff3\012\ufff3\001" +
    "\002\000\004\102\172\001\002\000\006\013\141\020\146" +
    "\001\002\000\012\004\ufffe\005\ufffe\013\ufffe\020\ufffe\001" +
    "\002\000\006\013\ufffc\020\ufffc\001\002\000\004\002\000" +
    "\001\002\000\004\070\150\001\002\000\006\013\ufffb\020" +
    "\ufffb\001\002\000\006\021\152\071\uffe1\001\002\000\006" +
    "\021\uffe3\071\uffe3\001\002\000\004\074\156\001\002\000" +
    "\006\021\152\071\154\001\002\000\004\002\uffe4\001\002" +
    "\000\006\021\uffe2\071\uffe2\001\002\000\004\102\157\001" +
    "\002\000\006\075\uffdf\077\uffdf\001\002\000\006\075\162" +
    "\077\161\001\002\000\004\102\171\001\002\000\004\022" +
    "\163\001\002\000\004\070\164\001\002\000\004\023\165" +
    "\001\002\000\004\076\166\001\002\000\004\101\167\001" +
    "\002\000\004\071\170\001\002\000\006\021\uffe0\071\uffe0" +
    "\001\002\000\006\075\uffde\077\uffde\001\002\000\004\070" +
    "\173\001\002\000\004\014\174\001\002\000\004\076\175" +
    "\001\002\000\004\074\176\001\002\000\004\102\177\001" +
    "\002\000\004\077\200\001\002\000\004\102\201\001\002" +
    "\000\004\075\202\001\002\000\004\077\203\001\002\000" +
    "\004\015\204\001\002\000\004\076\205\001\002\000\004" +
    "\101\206\001\002\000\004\077\207\001\002\000\004\016" +
    "\210\001\002\000\004\076\254\001\002\000\004\017\212" +
    "\001\002\000\004\076\215\001\002\000\004\071\214\001" +
    "\002\000\006\013\uffeb\020\uffeb\001\002\000\004\070\216" +
    "\001\002\000\004\045\217\001\002\000\004\076\220\001" +
    "\002\000\004\074\221\001\002\000\006\055\016\056\074" +
    "\001\002\000\006\075\uffe8\077\uffe8\001\002\000\006\075" +
    "\226\077\225\001\002\000\006\075\uffe6\077\uffe6\001\002" +
    "\000\006\055\016\056\074\001\002\000\004\077\227\001" +
    "\002\000\004\044\230\001\002\000\004\076\231\001\002" +
    "\000\004\101\232\001\002\000\004\077\233\001\002\000" +
    "\004\047\234\001\002\000\004\076\235\001\002\000\004" +
    "\074\236\001\002\000\006\055\016\056\074\001\002\000" +
    "\006\075\240\077\225\001\002\000\004\077\241\001\002" +
    "\000\004\046\242\001\002\000\004\076\243\001\002\000" +
    "\004\101\244\001\002\000\004\077\245\001\002\000\004" +
    "\050\246\001\002\000\004\076\247\001\002\000\004\101" +
    "\250\001\002\000\004\071\251\001\002\000\004\071\uffe9" +
    "\001\002\000\006\075\uffe7\077\uffe7\001\002\000\006\075" +
    "\uffe5\077\uffe5\001\002\000\004\070\255\001\002\000\004" +
    "\037\256\001\002\000\004\076\257\001\002\000\004\101" +
    "\260\001\002\000\004\077\261\001\002\000\004\040\262" +
    "\001\002\000\004\076\263\001\002\000\004\101\264\001" +
    "\002\000\004\077\265\001\002\000\004\041\266\001\002" +
    "\000\004\076\267\001\002\000\004\101\270\001\002\000" +
    "\004\077\271\001\002\000\004\042\272\001\002\000\004" +
    "\076\273\001\002\000\004\101\274\001\002\000\004\077" +
    "\275\001\002\000\004\043\276\001\002\000\004\076\277" +
    "\001\002\000\004\101\300\001\002\000\004\071\301\001" +
    "\002\000\004\017\uffea\001\002\000\004\002\001\001\002" +
    "\000\004\070\304\001\002\000\004\006\305\001\002\000" +
    "\004\076\306\001\002\000\004\056\074\001\002\000\004" +
    "\007\311\001\002\000\004\071\327\001\002\000\004\076" +
    "\312\001\002\000\004\074\313\001\002\000\006\010\316" +
    "\012\uffed\001\002\000\006\010\316\012\322\001\002\000" +
    "\006\010\uffef\012\uffef\001\002\000\046\024\041\025\050" +
    "\026\052\027\046\030\047\031\032\032\054\033\040\036" +
    "\051\051\042\052\027\053\036\054\044\067\035\072\056" +
    "\100\031\101\053\102\043\001\002\000\004\011\320\001" +
    "\002\000\004\056\074\001\002\000\010\010\uffec\012\uffec" +
    "\077\uffec\001\002\000\004\056\074\001\002\000\004\077" +
    "\324\001\002\000\006\010\uffee\012\uffee\001\002\000\004" +
    "\075\326\001\002\000\004\071\ufff0\001\002\000\012\004" +
    "\ufff8\005\ufff8\013\ufff8\020\ufff8\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\325\000\010\002\004\003\006\005\005\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\004\141\005\142\006\143\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\010\014\001\001\000\004\012\017\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\013\024\014\023\001\001\000" +
    "\004\013\133\001\001\000\002\001\001\000\020\026\033" +
    "\027\027\030\044\031\054\032\036\033\032\034\056\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\032\121\033\032\034\056\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\020\026\057\027" +
    "\027\030\044\031\054\032\036\033\032\034\056\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\031\062\032\036\033\032\034\056\001\001\000\002" +
    "\001\001\000\004\035\064\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\035\071\001\001\000\002\001\001\000\006\010\074\011" +
    "\075\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\032" +
    "\113\033\032\034\056\001\001\000\010\032\112\033\032" +
    "\034\056\001\001\000\010\032\111\033\032\034\056\001" +
    "\001\000\010\032\110\033\032\034\056\001\001\000\010" +
    "\032\107\033\032\034\056\001\001\000\010\032\106\033" +
    "\032\034\056\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\035\115\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\010\123\001\001\000\002\001\001" +
    "\000\014\030\125\031\054\032\036\033\032\034\056\001" +
    "\001\000\002\001\001\000\004\035\127\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\010\135\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\006\146\007\144\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\023\152\024\150\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\024\154\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\025\157\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\020\210\001\001\000\002" +
    "\001\001\000\004\021\212\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\010" +
    "\221\011\223\022\222\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\010\251\011\252\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\010\221\011\223" +
    "\022\236\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\011\306\001\001\000\004\015" +
    "\307\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\016\314\017\313\001\001\000\004\016" +
    "\322\001\001\000\002\001\001\000\020\026\316\027\027" +
    "\030\044\031\054\032\036\033\032\034\056\001\001\000" +
    "\002\001\001\000\004\011\320\001\001\000\002\001\001" +
    "\000\004\011\324\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {

    return lexer.next_token();

    }


    private Lexer lexer;
    private List<Error> errors = new ArrayList<>();

    public Parser(Lexer lexer) {
        super(lexer);
        this.lexer = lexer;
    }

    public Lexer getLexer() {
        return this.lexer;
    }

    public List<Error> getErrors() {
        List<Error> all = new ArrayList<>(lexer.getLexicalErrors());
        all.addAll(errors);
        return all;
    }

    public void report_error(String message, Object info) {
        if (info instanceof Symbol) {
            Symbol s = (Symbol) info;
            // Obtener el lexema del token
            String tokenValue = (s.value != null) ? s.value.toString() : "''";
            // Obtener el nombre del tipo de token (usando sym.terminalNames)
            String tokenType = "DESCONOCIDO";
            if (s.sym >= 0 && s.sym < sym.terminalNames.length) {
                tokenType = sym.terminalNames[s.sym];
            }
            // Construir mensaje con el token y su tipo
            String fullMessage = message + " (token: '" + tokenValue + "' tipo: " + tokenType + ")";
            errors.add(new Error("Sintáctico", fullMessage, s.left, s.right));
        } else {
            errors.add(new Error("Sintáctico", message, 0, 0));
        }
    }

    @Override
    public void syntax_error(Symbol currentToken) {
        report_error("Token inesperado durante el análisis", currentToken);
    }

    @Override
    public void unrecovered_syntax_error(Symbol currentToken) throws Exception {
        report_error("No fue posible recuperar el análisis desde este token", currentToken);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= lista_estrategias lista_partidas main 
            {
              Object RESULT =null;
		int leleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int leright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List le = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int lpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List lp = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int mleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int mright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		List m = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                 ProgramStore.getInstance().setStrategies(le);
                 ProgramStore.getInstance().setMatches(lp);
                 ProgramStore.getInstance().setMain(m);
             
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // lista_estrategias ::= estrategia 
            {
              List RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Strategy e = (Strategy)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                          List<Strategy> list = new ArrayList<>();
                          list.add(e);
                          RESULT = list;
                      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_estrategias",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_estrategias ::= lista_estrategias estrategia 
            {
              List RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List l = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Strategy e = (Strategy)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                          l.add(e);
                          RESULT = l;
                      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_estrategias",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // lista_estrategias ::= 
            {
              List RESULT =null;
		
                          RESULT = new ArrayList<>();
                      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_estrategias",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // lista_partidas ::= partida 
            {
              List RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Match p = (Match)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                       List<Match> list = new ArrayList<>();
                       list.add(p);
                       RESULT = list;
                   
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_partidas",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // lista_partidas ::= lista_partidas partida 
            {
              List RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List l = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Match p = (Match)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                       l.add(p);
                       RESULT = l;
                   
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_partidas",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // lista_partidas ::= 
            {
              List RESULT =null;
		
                       RESULT = new ArrayList<>();
                   
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_partidas",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // estrategia ::= MAGE ID LLAVEA INITIAL OJOS accion_mago reglas_mago LLAVEC 
            {
              Strategy RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int inileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int iniright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Action ini = (Action)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List r = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                   Strategy s = new Strategy(nombre, ClassType.MAGE, ini, r);
                   RESULT = s;
               
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("estrategia",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // estrategia ::= WARRIOR ID LLAVEA INITIAL OJOS accion_guerrero reglas_guerrero LLAVEC 
            {
              Strategy RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int inileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int iniright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Action ini = (Action)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List r = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                   Strategy s = new Strategy(nombre, ClassType.WARRIOR, ini, r);
                   RESULT = s;
               
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("estrategia",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // accion_mago ::= MAGE_ACTION 
            {
              Action RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                    RESULT = Action.fromString(s);
                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion_mago",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // accion_guerrero ::= WARRIOR_ACTION 
            {
              Action RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                        RESULT = Action.fromString(s);
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion_guerrero",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // reglas_mago ::= RULES OJOS CORCHETEA lista_reglas_mago ELSE accion_mago CORCHETEC 
            {
              List RESULT =null;
		int rlleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int rlright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		List rl = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int defleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int defright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Action def = (Action)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                    rl.add(new ElseRule(def));
                    RESULT = rl;
                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("reglas_mago",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // lista_reglas_mago ::= regla_mago 
            {
              List RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Rule r = (Rule)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                          List<Rule> list = new ArrayList<>();
                          list.add(r);
                          RESULT = list;
                      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_reglas_mago",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // lista_reglas_mago ::= lista_reglas_mago regla_mago COMA 
            {
              List RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List l = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Rule r = (Rule)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                          l.add(r);
                          RESULT = l;
                      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_reglas_mago",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // lista_reglas_mago ::= 
            {
              List RESULT =null;
		
                          RESULT = new ArrayList<>();
                      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_reglas_mago",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // regla_mago ::= IF expresion THEN accion_mago 
            {
              Rule RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Action a = (Action)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                   RESULT = new IfRule(e, a);
               
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("regla_mago",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // reglas_guerrero ::= RULES OJOS CORCHETEA lista_reglas_guerrero ELSE accion_guerrero CORCHETEC 
            {
              List RESULT =null;
		int rlleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int rlright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		List rl = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int defleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int defright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Action def = (Action)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                        rl.add(new ElseRule(def));
                        RESULT = rl;
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("reglas_guerrero",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // lista_reglas_guerrero ::= regla_guerrero 
            {
              List RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Rule r = (Rule)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                              List<Rule> list = new ArrayList<>();
                              list.add(r);
                              RESULT = list;
                          
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_reglas_guerrero",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // lista_reglas_guerrero ::= lista_reglas_guerrero regla_guerrero COMA 
            {
              List RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List l = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Rule r = (Rule)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                              l.add(r);
                              RESULT = l;
                          
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_reglas_guerrero",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // lista_reglas_guerrero ::= 
            {
              List RESULT =null;
		
                              RESULT = new ArrayList<>();
                          
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_reglas_guerrero",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // regla_guerrero ::= IF expresion THEN accion_guerrero 
            {
              Rule RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Action a = (Action)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                       RESULT = new IfRule(e, a);
                   
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("regla_guerrero",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // partida ::= MATCH ID LLAVEA PLAYERS OJOS CORCHETEA ID COMA ID CORCHETEC COMA ROUNDS OJOS ENTERO COMA bloque_scoring bloque_bonuses LLAVEC 
            {
              Match RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-16)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-16)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-16)).value;
		int p1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-11)).left;
		int p1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-11)).right;
		String p1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-11)).value;
		int p2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)).left;
		int p2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)).right;
		String p2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-9)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Integer r = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int scleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int scright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Scoring sc = (Scoring)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bonleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bonright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Bonuses bon = (Bonuses)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                Match m = new Match(nombre, p1, p2, r, sc, bon);
                RESULT = m;
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("partida",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-17)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // bloque_scoring ::= SCORING OJOS LLAVEA DAMAGE_POINT OJOS ENTERO COMA HEALING_POINT OJOS ENTERO COMA SUCCESSFUL_DEFENSE OJOS ENTERO COMA VICTORY_BONUS OJOS ENTERO COMA FAILED_ACTION_PENALTY OJOS ENTERO LLAVEC 
            {
              Scoring RESULT =null;
		int dpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-17)).left;
		int dpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-17)).right;
		Integer dp = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-17)).value;
		int hpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-13)).left;
		int hpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-13)).right;
		Integer hp = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-13)).value;
		int sdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)).left;
		int sdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)).right;
		Integer sd = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-9)).value;
		int vbleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int vbright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		Integer vb = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int fpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int fpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Integer fp = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                       RESULT = new Scoring(dp, hp, sd, vb, fp);
                   
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_scoring",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-22)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // bloque_bonuses ::= BONUSES OJOS LLAVEA MAGE_COMBO OJOS CORCHETEA lista_acciones CORCHETEC COMA MAGE_COMBO_POINTS OJOS ENTERO COMA WARRIOR_COMBO OJOS CORCHETEA lista_acciones CORCHETEC COMA WARRIOR_COMBO_POINTS OJOS ENTERO COMA LOW_HEALTH_VICTORY OJOS ENTERO LLAVEC 
            {
              Bonuses RESULT =null;
		int mcleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-20)).left;
		int mcright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-20)).right;
		List mc = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-20)).value;
		int mcpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-15)).left;
		int mcpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-15)).right;
		Integer mcp = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-15)).value;
		int wcleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)).left;
		int wcright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)).right;
		List wc = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-10)).value;
		int wcpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int wcpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		Integer wcp = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int lhvleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lhvright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Integer lhv = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                       RESULT = new Bonuses(mc, mcp, wc, wcp, lhv);
                   
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_bonuses",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-26)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // lista_acciones ::= accion_mago 
            {
              List RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Action a = (Action)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                       List<Action> list = new ArrayList<>();
                       list.add(a);
                       RESULT = list;
                   
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_acciones",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // lista_acciones ::= lista_acciones COMA accion_mago 
            {
              List RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List l = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Action a = (Action)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                       l.add(a);
                       RESULT = l;
                   
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_acciones",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // lista_acciones ::= accion_guerrero 
            {
              List RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Action a = (Action)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                       List<Action> list = new ArrayList<>();
                       list.add(a);
                       RESULT = list;
                   
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_acciones",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // lista_acciones ::= lista_acciones COMA accion_guerrero 
            {
              List RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List l = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Action a = (Action)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                       l.add(a);
                       RESULT = l;
                   
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_acciones",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // main ::= MAIN LLAVEA lista_run LLAVEC 
            {
              List RESULT =null;
		int lrleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lrright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List lr = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
             RESULT = lr;
         
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("main",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // lista_run ::= instruccion_run 
            {
              List RESULT =null;
		int irleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int irright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		RunInstruction ir = (RunInstruction)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                  List<RunInstruction> list = new ArrayList<>();
                  list.add(ir);
                  RESULT = list;
              
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_run",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // lista_run ::= lista_run instruccion_run 
            {
              List RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List l = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int irleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int irright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		RunInstruction ir = (RunInstruction)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                  l.add(ir);
                  RESULT = l;
              
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_run",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // lista_run ::= 
            {
              List RESULT =null;
		
                  RESULT = new ArrayList<>();
              
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_run",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // instruccion_run ::= RUN CORCHETEA lista_ids CORCHETEC WITH LLAVEA SEED OJOS ENTERO LLAVEC 
            {
              RunInstruction RESULT =null;
		int idsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int idsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		List ids = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int seedleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int seedright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Integer seed = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                        RESULT = new RunInstruction(ids, seed);
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_run",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // lista_ids ::= ID 
            {
              List RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                  List<String> list = new ArrayList<>();
                  list.add(id);
                  RESULT = list;
              
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_ids",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // lista_ids ::= lista_ids COMA ID 
            {
              List RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List l = (List)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                  l.add(id);
                  RESULT = l;
              
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_ids",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expresion ::= expresion_or 
            {
              Expression RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expresion_or ::= expresion_or OR expresion_and 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new BinaryExpression(e1, "||", e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_or",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expresion_or ::= expresion_and 
            {
              Expression RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_or",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expresion_and ::= expresion_and AND expresion_comparacion 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new BinaryExpression(e1, "&&", e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_and",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expresion_and ::= expresion_comparacion 
            {
              Expression RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_and",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expresion_comparacion ::= expresion_unaria EQ expresion_unaria 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new BinaryExpression(e1, "==", e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_comparacion",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expresion_comparacion ::= expresion_unaria NEQ expresion_unaria 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new BinaryExpression(e1, "!=", e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_comparacion",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expresion_comparacion ::= expresion_unaria LT expresion_unaria 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new BinaryExpression(e1, "<", e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_comparacion",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expresion_comparacion ::= expresion_unaria GT expresion_unaria 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new BinaryExpression(e1, ">", e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_comparacion",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expresion_comparacion ::= expresion_unaria LE expresion_unaria 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new BinaryExpression(e1, "<=", e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_comparacion",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expresion_comparacion ::= expresion_unaria GE expresion_unaria 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new BinaryExpression(e1, ">=", e2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_comparacion",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expresion_comparacion ::= expresion_unaria 
            {
              Expression RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_comparacion",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expresion_unaria ::= NOT expresion_unaria 
            {
              Expression RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new UnaryExpression("!", e); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_unaria",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expresion_unaria ::= expresion_primaria 
            {
              Expression RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_unaria",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expresion_primaria ::= ENTERO 
            {
              Expression RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ConstantExpression(i); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expresion_primaria ::= DECIMAL 
            {
              Expression RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Double d = (Double)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ConstantExpression(d); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expresion_primaria ::= SELF_HEALTH 
            {
              Expression RESULT =null;
		 RESULT = new VariableExpression("self_health"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expresion_primaria ::= OPPONENT_HEALTH 
            {
              Expression RESULT =null;
		 RESULT = new VariableExpression("opponent_health"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expresion_primaria ::= SELF_RESOURCE 
            {
              Expression RESULT =null;
		 RESULT = new VariableExpression("self_resource"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expresion_primaria ::= OPPONENT_RESOURCE 
            {
              Expression RESULT =null;
		 RESULT = new VariableExpression("opponent_resource"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expresion_primaria ::= SELF_SCORE 
            {
              Expression RESULT =null;
		 RESULT = new VariableExpression("self_score"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expresion_primaria ::= OPPONENT_SCORE 
            {
              Expression RESULT =null;
		 RESULT = new VariableExpression("opponent_score"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expresion_primaria ::= ROUND_NUMBER 
            {
              Expression RESULT =null;
		 RESULT = new VariableExpression("round_number"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expresion_primaria ::= TOTAL_ROUNDS 
            {
              Expression RESULT =null;
		 RESULT = new VariableExpression("total_rounds"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expresion_primaria ::= RANDOM 
            {
              Expression RESULT =null;
		 RESULT = new VariableExpression("random"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expresion_primaria ::= ID 
            {
              Expression RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new VariableExpression(id); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expresion_primaria ::= funcion 
            {
              Expression RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expression f = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = f; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expresion_primaria ::= PARENTESISA expresion PARENTESISC 
            {
              Expression RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // funcion ::= GET_MOVE PARENTESISA historial COMA ENTERO PARENTESISC 
            {
              Expression RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String h = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new FunctionCall("get_move", h, n); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // funcion ::= LAST_MOVE PARENTESISA historial PARENTESISC 
            {
              Expression RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String h = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new FunctionCall("last_move", h); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // funcion ::= GET_MOVES_COUNT PARENTESISA historial COMA accion_mago PARENTESISC 
            {
              Expression RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String h = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Action a = (Action)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new FunctionCall("get_moves_count", h, a); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // funcion ::= GET_MOVES_COUNT PARENTESISA historial COMA accion_guerrero PARENTESISC 
            {
              Expression RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String h = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Action a = (Action)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new FunctionCall("get_moves_count", h, a); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // funcion ::= GET_LAST_N_MOVES PARENTESISA historial COMA ENTERO PARENTESISC 
            {
              Expression RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String h = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new FunctionCall("get_last_n_moves", h, n); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // historial ::= SELF_HISTORY 
            {
              String RESULT =null;
		 RESULT = "self"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("historial",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // historial ::= OPPONENT_HISTORY 
            {
              String RESULT =null;
		 RESULT = "opponent"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("historial",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
