<?xml version="1.0" encoding="UTF-8"?>
<project name="BattleScript" default="default" basedir=".">
    <description>Builds, tests, and runs the project BattleScript.</description>
    <import file="nbproject/build-impl.xml"/>
    <property name="cup" location="src/cup"/>
    <property name="jflex" location="src/jflex"/>
    <property name="java" location="src"/>    
    <property name="lib" location="../lib"/>
        
    <taskdef name="jflex" classname="jflex.anttask.JFlexTask" classpath="${lib}/jflex-full-1.9.1.jar"/>
    <taskdef name="cup" classname="java_cup.anttask.CUPTask" classpath="${lib}/java-cup-11b.jar"/> 
    
    <!-- Generar Lexer y Parser antes de compilar -->
    <target name="-pre-compile" depends="generate"/>
    <target name="generate">
        
        <jflex file="${jflex}/Lexer.jflex" destdir="${java}/analyzer"/>
        
        <cup srcfile="${cup}/Parser.cup"
             destdir="${java}"
             parser="Parser"
             interface="true"
             locations="false"
             expect="6"
             force="true"/>
        
    </target>
    
    <!-- Eliminar archivos generados al hacer Clean -->
    <target name="-post-clean">
        
        <delete file="${java}/analyzer/Lexer.java" quiet="true"/>
        <delete file="${java}/analyzer/Parser.java" quiet="true"/>
        <delete file="${java}/analyzer/sym.java" quiet="true"/>
        <delete file="${java}/analyzer/ParserSym.java" quiet="true"/>
        
    </target>
</project>
